server:
  port: 8080
spring:
  datasource:
    name: Wind
    url: jdbc:mysql://192.168.1.128:3306/Wind?characterEncoding=utf-8&useSSL=false
    username: root
    password: Admin888@
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql

mybatis:
  mapper-locations: classpath:mapper/*.xml